# Generated by Django 2.2.5 on 2019-09-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('docid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('signee', models.CharField(max_length=64)),
            ],
        ),
    ]
