# Generated by Django 2.2.5 on 2019-09-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('visual_fingerprint', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='signee',
        ),
        migrations.AddField(
            model_name='document',
            name='signer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Signer'),
        ),
    ]
