# Generated by Django 2.2.5 on 2019-09-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190915_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='terms',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
