# Generated by Django 2.2.5 on 2019-09-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
