# Generated by Django 2.2.5 on 2019-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='clickwrap_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
